# Human readable name of this type
name: Products

# Lowercase, underscored handle used to access this type
slug: products

# Explanatory text displayed in the back-office
description: List all the products displayed in the website

# Slug of field used to identify entries by default, such as the title
label_field_name: name

# Valid values: manually, created_at, updated_at, or the slug of any field
order_by: manually

# Valid values: asc (ascending) and desc (descending). Set to asc by default.
# order_direction: asc

# Specify a field slug to group entries by that field in the back-office.
# group_by: <your field>

# Activate public 'create' API (e.g for a contact form)
# public_submission_enabled: false

# Array of emails to be notified of new entries made with the public API
# public_submission_accounts: ['john@example.com']

# Control the display of the content type in the back-office.
display_settings:
  # seo: false              # display the SEO tab for the content entries
  # advanced: false         # display the Advanced tab for the content entries
  position: 1             # position in the sidebar menu
  # hidden: false           # hidden for authors?

# By default, the back-office displays the _label property (see label_field_name) of the content entry. This can be modified by writing your own Liquid template below:
entry_template: '<a href="{{ link }}">{{ entry._label }}</a>{% if entry.featured %}&nbsp;&nbsp;<span class="label label-success">FEATURED</span>{% endif %}' # The default template

# A list describing each field
fields:
- name: # The lowercase, underscored name of the field
    label: Name # Human readable name of the field
    type: string
    required: true
    hint: Name of the product
    localized: false

- featured:
    label: Featured
    type: boolean
    hint: "Toggle it on if you want to product to be displayed on the home page"

- price: # The lowercase, underscored name of the field
    label: Price # Human readable name of the field
    type: float
    required: false
    hint: "The currency is specified in the templates."
    localized: false

- picture: # The lowercase, underscored name of the field
    label: Picture # Human readable name of the field
    type: file
    required: false
    hint: Best format is 600px by 600px.
    localized: false

- weight: # The lowercase, underscored name of the field
    label: Weight # Human readable name of the field
    type: integer
    required: false
    hint: In kilograms
    localized: false

- short_description: # The lowercase, underscored name of the field
    label: Short description # Human readable name of the field
    type: string
    required: false
    hint: That description will be used to describe the product once in the cart.
    localized: false

- description: # The lowercase, underscored name of the field
    label: Description # Human readable name of the field
    type: text
    required: false
    hint: "Full description of the product"
    localized: false
    text_formatting: html # html (uses rich text editor), markdown or text (uses plain text editor)

- related_products:
    label: Related Products
    type: many_to_many
    class_name: products
    inverse_of: related_products
    ui_enabled: true
